[package]
name = "random_secret"
version = "0.1.0"
authors = ["Kennedy Kariuki <kennedy.kariuki@tracom.co.ke>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
